source_name: "Road Cameras (One Camera)"
source_type: "video"
source_mode: "rtsp_video"
source_list:
  - name: "road_camera_0"
    url: ""
    dir: "road_0/"
    metadata:
      resolution: "540p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 4

