source_name: "Road Dense HTTP"
source_type: "video"
source_mode: "http_video"
source_list:
  - name: "road_camera_dense"
    url: ""
    dir: "road_dense/"
    metadata:
      resolution: "540p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 4

