source_name: "Street Sparse HTTP"
source_type: "video"
source_mode: "http_video"
source_list:
  - name: "street_camera_sparse"
    url: ""
    dir: "street_sparse"
    metadata:
      resolution: "1080p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 4


