source_name: "Street Camera (One Camera, HTTP)"
source_type: "video"
source_mode: "http_video"
source_list:
  - name: "street_camera_0"
    url: ""
    dir: "street_0"
    metadata:
      resolution: "1080p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 4


