namespace: dayu
log-level: DEBUG
log-file-name:
pod-permission:
  service-account: worker-admin
  cluster-role-binding: worker-admin-binding
crd-meta:
  api-version: sedna.io/v1alpha1
  kind: JointMultiEdgeService
default-image-meta:
  registry: repo:5000
  repository: dayuhub
  tag: v1.1
default-file-mount-prefix: "/data/dayu-files"
datasource:
  use-simulation: true
  node: edgex1
  data-root: "/data/datasource/"
  play-mode: non-cycle
scheduler-policies:
  !include scheduler_policies.yaml
services:
  !include services.yaml
visualizations:
  !include visualizations.yaml


