# Template of buildkitd.toml for docker buildx.
# Default buildkitd.toml is empty.
# If you want to use http registry or proxy when buildx docker images, please modify buildkitd.toml as the following templates.


# use http registry
insecure-entitlements=["114.212.87.136:5000","repo:5000"]

[registry."repo:5000"]
  http = true
  insecure = true

[registry."114.212.87.136:5000"]
  http = true
  insecure = true


# use proxy
[worker]
  [worker.docker]
    network = "default"

  [worker.env]
    HTTP_PROXY = "http://192.168.3.5:7890"
    HTTPS_PROXY = "http://192.168.3.5:7890"
    NO_PROXY = "localhost,127.0.0.1,.example.com,114.212.87.136"

